

services:
  dashboard:
    build:
      context: src/frontend
      dockerfile: Dockerfile  # Specify the Dockerfile if not named 'Dockerfile'

    volumes:
      - db:/app/dbs

    ports:
      - "8000:8000"

  update_db:
    build:
      context: src/backend
      dockerfile: Dockerfile
    volumes:
      - C:/Users/shoam/OneDrive/Desktop/random folder:/update_db/local_data

    ports:
      - "8050:8050"
  sql_server_db:
    image: mcr.microsoft.com/mssql/server
    environment:
      UID: "hello"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "asafba"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"




volumes:
  db:
