
networks:
  app-tier:
    driver: bridge
services:
  dashboard:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    depends_on:
      postgresdb:
        condition: service_healthy

    environment:
      - POSTGRES_DB=files_db
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=Asafba123
    volumes:
      - db:/app/dbs

    ports:
      - "8000:8000"

  update-db:
    depends_on:
      postgresdb:
        condition: service_healthy
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=files_db
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=Asafba123
    volumes:
      - C:/Users/shoam/OneDrive/Desktop/randomfolder:/update-db/local-data

    ports:
      - "8050:8050"
  postgresdb:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_DB=files_db
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=Asafba123
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 5s
        timeout: 5s
        retries: 5
    ports:
      - "5432:5432"

volumes:
  db:
