
networks:
  app-tier:
    driver: bridge
services:
  dashboard:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    depends_on:
      postgresdb:
        condition: service_healthy

    environment:
      - DB_NAME=files_db
      - DB_USERNAME=hello
      - DB_PASSWORD=Asafba123
      - DB_HOST=postgresdb
    volumes:
      - db:/app/dbs

    ports:
      - "8000:8000"

  update_db:
    depends_on:
      postgresdb:
        condition: service_healthy
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    environment:
      - DB_NAME=files_db
      - DB_USERNAME=hello
      - DB_PASSWORD=Asafba123
      - DB_HOST=postgresdb
    volumes:
      - C:/Users/shoam/OneDrive/Desktop/random folder:/update_db/local_data

    ports:
      - "8050:8050"
  postgresdb:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_DB=files_db
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=Asafba123
      - POSTGRES_HOST=postgresdb
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 5s
        timeout: 5s
        retries: 5
    ports:
      - "5432:5432"





volumes:
  db:
