
networks:
  app-tier:
    driver: bridge
services:
  dashboard:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile  # Specify the Dockerfile if not named 'Dockerfile'

    volumes:
      - db:/app/dbs

    ports:
      - "8000:8000"

  update_db:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    volumes:
      - C:/Users/shoam/OneDrive/Desktop/random folder:/update_db/local_data

    ports:
      - "8050:8050"
  sql_server_db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_DB: "hello"
      POSTGRESQL_USERNAME: "Developer"
      POSTGRESQL_PASSWORD: "Asafba123!"
    ports:
      - "5432:5432"




volumes:
  db:
