apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  name: dashboard
  labels:
    app: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        app: dashboard
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'sleep 90']
      containers:
        - image: shohambo/dashboard:news
          name: dashboard
          env:
            - name: POSTGRES_DB
              value: files_db
            - name: POSTGRES_USER
              value: hello
            - name: POSTGRES_PASSWORD
              value: Asafba123
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  name: dashboard
  labels:
    app: dashboard
spec:
  type: NodePort
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: dashboard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  name: update-db
  labels:
    app: update-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: update-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: update-db
      annotations:
        kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'sleep 70']
      containers:
      - image: shohambo/update-db:news
        name: update-db
        ports:
        - containerPort: 8050
          protocol: TCP
        env:
          - name: POSTGRES_DB
            value: files_db
          - name: POSTGRES_USER
            value: hello
          - name: POSTGRES_PASSWORD
            value: Asafba123
        volumeMounts:
        - name: local-data
          mountPath: /update-db/local-data
      volumes:
      - name: local-data
        hostPath:
          path: /mnt/c/Users/shoam/OneDrive/Desktop/randomfolder
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  name: update-db
  labels:
    app: update-db
spec:
  ports:
    - name: "8050"
      port: 8050
      targetPort: 8050
  selector:
    app: update-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  name: postgresdb
  labels:
    app: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
      annotations:
        kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
    spec:
      containers:
        - image: bitnami/postgresql:latest
          name: postgresdb
          env:
            - name: POSTGRES_DB
              value: files_db
            - name: POSTGRES_USER
              value: hello
            - name: POSTGRES_PASSWORD
              value: Asafba123
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  name: postgresdb
  labels:
    app: postgresdb
spec:
  type: ClusterIP
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: postgresdb