apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: dashboard
  name: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dashboard
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: dashboard
    spec:
      containers:
        - env:
            - name: DB_NAME
              value: files_db
            - name: DB_PASSWORD
              value: Asafba123
            - name: DB_USERNAME
              value: hello
          image: dashboard
          name: dashboard
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: dashboard
  name: dashboard
spec:
  type: NodePort
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
      nodePort: 30000
  selector:
    io.kompose.service: dashboard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: update-db
  name: update-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: update-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: update-db
    spec:
      containers:
        - env:
            - name: DB_NAME
              value: files_db
            - name: DB_PASSWORD
              value: Asafba123
            - name: DB_USERNAME
              value: hello
          image: update-db
          name: update-db
          ports:
            - containerPort: 8050
              protocol: TCP
          volumeMounts:
            - mountPath: C:/Users/shoam/OneDrive/Desktop/random folder:/update-db/local_data
              name: local_data
      restartPolicy: Always
      volumes:
        - configMap:
            name: update-db
          name: update-db
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: update-db
  name: update-db
spec:
  ports:
    - name: "8050"
      port: 8050
      targetPort: 8050
  selector:
    io.kompose.service: update-db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: postgres-db
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-db
  template:
    metadata:
      annotations:
        kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: postgres-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: files_db
            - name: POSTGRES_PASSWORD
              value: Asafba123
            - name: POSTGRES_USERNAME
              value: hello
          image: bitnami/postgresql:latest
          livenessProbe:
            exec:
              command:
                - pg_isready -U postgres
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          name: postgres-db
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: postgres-db
  name: postgres-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: postgres-db
---
