apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  name: dashboard
  labels:
    app: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        app: dashboard
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'sleep 90']
      containers:
        - image: shohambo/dashboard:news
          name: dashboard
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-data
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-data
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-data
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  name: dashboard
  labels:
    app: dashboard
spec:
  type: NodePort
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: dashboard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  name: update-db
  labels:
    app: update-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: update-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: update-db
      annotations:
        kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
    spec:
#      initContainers:
#        - name: wait-for-db
#          image: busybox
#          command: ['sh', '-c', 'sleep 70']
      containers:
      - image: shohambo/update-db:news
        name: update-db
        ports:
        - containerPort: 8050
          protocol: TCP
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: db-data
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: db-data
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-data
                key: POSTGRES_PASSWORD
        volumeMounts:
        - name: local-data
          mountPath: /update-db/local-data
      volumes:
      - name: local-data
        hostPath:
          path: /mnt/data
          type: Directory

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  name: update-db
  labels:
    app: update-db
spec:
  ports:
    - name: "8050"
      port: 8050
      targetPort: 8050
  selector:
    app: update-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  name: postgresdb
  labels:
    app: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
      annotations:
        kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
    spec:
      containers:
        - image: bitnami/postgresql:latest
          name: postgresdb
          env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: db-data
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: db-data
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-data
                key: POSTGRES_PASSWORD
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  name: postgresdb
  labels:
    app: postgresdb
spec:
  type: ClusterIP
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: postgresdb
---
apiVersion: v1
kind: Secret
metadata:
  name: db-data
data:
  POSTGRES_DB: ZmlsZXNfZGJfY29uZmln
  POSTGRES_USER: aGVsbG8=
  POSTGRES_PASSWORD: QXNhZmJhMTIz