apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  name: dashboard
  labels:
    app: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        app: dashboard
    spec:
      containers:
        - image: dashboard  # Local image name
          name: dashboard
          env:
            - name: DB_NAME
              value: files_db
            - name: DB_PASSWORD
              value: Asafba123
            - name: DB_USERNAME
              value: hello
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  name: dashboard
  labels:
    app: dashboard
spec:
  type: NodePort
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
      nodePort: 30000
  selector:
    app: dashboard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  name: update-db
  labels:
    app: update-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: update-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: update-db
      annotations:
        kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
    spec:
      containers:
      - name: update-db
        image: update-db
        imagePullPolicy: Never
        ports:
        - containerPort: 8050
          protocol: TCP
        env:
        - name: DB_NAME
          value: files_db
        - name: DB_PASSWORD
          value: Asafba123
        - name: DB_USERNAME
          value: hello
        volumeMounts:
        - name: local-data
          mountPath: /update-db/local_data
      volumes:
      - name: local-data
        hostPath:
          path: /mnt/c/Users/shoam/OneDrive/Desktop/random folder
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  name: update-db
  labels:
    app: update-db
spec:
  ports:
    - name: "8050"
      port: 8050
      targetPort: 8050
  selector:
    app: update-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  name: postgres-db
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
      annotations:
        kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: files_db
            - name: POSTGRES_PASSWORD
              value: Asafba123
            - name: POSTGRES_USER  # Updated environment variable
              value: hello
          image: bitnami/postgresql:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - pg_isready -U postgres
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          name: postgres-db
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe --file compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  name: postgres-db
  labels:
    app: postgres-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres-db